package main

import (
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

// --- rootCmd ------------------------------------------------------------------

func TestRootCmd_BasicAttributes(t *testing.T) {
	if rootCmd.Use != "onecloudriver" {
		t.Errorf("expected Use 'onecloudriver', got %q", rootCmd.Use)
	}

	if !strings.Contains(rootCmd.Short, "OneDrive") {
		t.Errorf("expected Short to mention OneDrive, got %q", rootCmd.Short)
	}

	if rootCmd.Version != version {
		t.Errorf("expected Version %q, got %q", version, rootCmd.Version)
	}
}

func TestRootCmd_HasAllSubcommands(t *testing.T) {
	expectedCmds := []string{
		"account",
		"mount",
		"service",
		"list",
		"info",
		"download",
		"mkdir",
		"rm",
		"rename",
		"mv",
		"copy",
		"upload",
		"sync",
	}

	cmdNames := make(map[string]bool)
	for _, cmd := range rootCmd.Commands() {
		cmdNames[cmd.Name()] = true
	}

	for _, name := range expectedCmds {
		if !cmdNames[name] {
			t.Errorf("expected subcommand %q not found in rootCmd", name)
		}
	}
}

func TestRootCmd_NoExtraSubcommands(t *testing.T) {
	expectedCmds := map[string]bool{
		"account":    true,
		"mount":      true,
		"service":    true,
		"list":       true,
		"info":       true,
		"download":   true,
		"mkdir":      true,
		"rm":         true,
		"rename":     true,
		"mv":         true,
		"copy":       true,
		"upload":     true,
		"sync":       true,
		"help":       true, // auto-generated by cobra
		"completion": true, // auto-generated by cobra
	}

	for _, cmd := range rootCmd.Commands() {
		if !expectedCmds[cmd.Name()] {
			t.Errorf("unexpected subcommand %q found in rootCmd", cmd.Name())
		}
	}
}

// --- account subcommands ------------------------------------------------------

func TestAccountCmd_HasSubcommands(t *testing.T) {
	accountCmd := findSubcommand(rootCmd, "account")
	if accountCmd == nil {
		t.Fatal("account subcommand not found")
	}

	expected := []string{"add", "list", "remove"}
	names := subcommandNames(accountCmd)

	for _, name := range expected {
		if !contains(names, name) {
			t.Errorf("expected account subcommand %q not found", name)
		}
	}
}

func TestAccountRemoveCmd_MutuallyExclusiveFlags(t *testing.T) {
	accountCmd := findSubcommand(rootCmd, "account")
	removeCmd := findSubcommand(accountCmd, "remove")
	if removeCmd == nil {
		t.Fatal("account remove subcommand not found")
	}

	purgeFlag := removeCmd.Flags().Lookup("purge")
	keepFlag := removeCmd.Flags().Lookup("keep")

	if purgeFlag == nil {
		t.Error("account remove missing --purge flag")
	}
	if keepFlag == nil {
		t.Error("account remove missing --keep flag")
	}

	// Verify they're booleans
	if purgeFlag != nil && purgeFlag.Value.Type() != "bool" {
		t.Errorf("--purge should be bool, got %s", purgeFlag.Value.Type())
	}
	if keepFlag != nil && keepFlag.Value.Type() != "bool" {
		t.Errorf("--keep should be bool, got %s", keepFlag.Value.Type())
	}
}

// --- service subcommands ------------------------------------------------------

func TestServiceCmd_HasSubcommands(t *testing.T) {
	serviceCmd := findSubcommand(rootCmd, "service")
	if serviceCmd == nil {
		t.Fatal("service subcommand not found")
	}

	expected := []string{"install", "uninstall", "status", "start", "stop"}
	names := subcommandNames(serviceCmd)

	for _, name := range expected {
		if !contains(names, name) {
			t.Errorf("expected service subcommand %q not found", name)
		}
	}
}

func TestServiceInstallCmd_HasAllFlags(t *testing.T) {
	serviceCmd := findSubcommand(rootCmd, "service")
	installCmd := findSubcommand(serviceCmd, "install")
	if installCmd == nil {
		t.Fatal("service install subcommand not found")
	}

	expectedFlags := []string{"mountpoint", "account", "enable", "all"}
	for _, flagName := range expectedFlags {
		if installCmd.Flags().Lookup(flagName) == nil {
			t.Errorf("service install missing --%s flag", flagName)
		}
	}
}

// --- command flags ------------------------------------------------------------

func TestListCmd_HasFlags(t *testing.T) {
	listCmd := findSubcommand(rootCmd, "list")
	if listCmd == nil {
		t.Fatal("list subcommand not found")
	}

	if listCmd.Flags().Lookup("account") == nil {
		t.Error("list missing --account flag")
	}
	if listCmd.Flags().Lookup("output") == nil {
		t.Error("list missing --output flag")
	}

	// Verify shorthand
	accountFlag := listCmd.Flags().Lookup("account")
	if accountFlag != nil && accountFlag.Shorthand != "a" {
		t.Errorf("list --account shorthand: expected 'a', got %q", accountFlag.Shorthand)
	}
	outputFlag := listCmd.Flags().Lookup("output")
	if outputFlag != nil && outputFlag.Shorthand != "o" {
		t.Errorf("list --output shorthand: expected 'o', got %q", outputFlag.Shorthand)
	}
}

func TestInfoCmd_HasIdPathMutualExclusion(t *testing.T) {
	infoCmd := findSubcommand(rootCmd, "info")
	if infoCmd == nil {
		t.Fatal("info subcommand not found")
	}

	if infoCmd.Flags().Lookup("id") == nil {
		t.Error("info missing --id flag")
	}
	if infoCmd.Flags().Lookup("path") == nil {
		t.Error("info missing --path flag")
	}
	if infoCmd.Flags().Lookup("output") == nil {
		t.Error("info missing --output flag")
	}
	if infoCmd.Flags().Lookup("account") == nil {
		t.Error("info missing --account flag")
	}
}

func TestDownloadCmd_HasAllFlags(t *testing.T) {
	downloadCmd := findSubcommand(rootCmd, "download")
	if downloadCmd == nil {
		t.Fatal("download subcommand not found")
	}

	expectedFlags := []string{"account", "id", "path", "output", "output-dir"}
	for _, flagName := range expectedFlags {
		if downloadCmd.Flags().Lookup(flagName) == nil {
			t.Errorf("download missing --%s flag", flagName)
		}
	}
}

func TestMkdirCmd_NameFlag(t *testing.T) {
	mkdirCmd := findSubcommand(rootCmd, "mkdir")
	if mkdirCmd == nil {
		t.Fatal("mkdir subcommand not found")
	}

	nameFlag := mkdirCmd.Flags().Lookup("name")
	if nameFlag == nil {
		t.Fatal("mkdir missing --name flag")
	}
	if nameFlag.Shorthand != "n" {
		t.Errorf("mkdir --name shorthand: expected 'n', got %q", nameFlag.Shorthand)
	}
}

func TestRmCmd_ForceFlag(t *testing.T) {
	rmCmd := findSubcommand(rootCmd, "rm")
	if rmCmd == nil {
		t.Fatal("rm subcommand not found")
	}

	forceFlag := rmCmd.Flags().Lookup("force")
	if forceFlag == nil {
		t.Fatal("rm missing --force flag")
	}
	if forceFlag.Shorthand != "f" {
		t.Errorf("rm --force shorthand: expected 'f', got %q", forceFlag.Shorthand)
	}
}

func TestRenameCmd_NameFlag(t *testing.T) {
	renameCmd := findSubcommand(rootCmd, "rename")
	if renameCmd == nil {
		t.Fatal("rename subcommand not found")
	}

	nameFlag := renameCmd.Flags().Lookup("name")
	if nameFlag == nil {
		t.Fatal("rename missing --name flag")
	}

	// Verify shorthand
	if nameFlag != nil && nameFlag.Shorthand != "n" {
		t.Errorf("rename --name shorthand: expected 'n', got %q", nameFlag.Shorthand)
	}

	// Verify other rename flags
	if renameCmd.Flags().Lookup("etag") == nil {
		t.Error("rename missing --etag flag")
	}
}

func TestMvCmd_HasDestFlags(t *testing.T) {
	mvCmd := findSubcommand(rootCmd, "mv")
	if mvCmd == nil {
		t.Fatal("mv subcommand not found")
	}

	expectedFlags := []string{"account", "id", "path", "dest-id", "dest-path", "etag"}
	for _, flagName := range expectedFlags {
		if mvCmd.Flags().Lookup(flagName) == nil {
			t.Errorf("mv missing --%s flag", flagName)
		}
	}
}

func TestCopyCmd_HasAllFlags(t *testing.T) {
	copyCmd := findSubcommand(rootCmd, "copy")
	if copyCmd == nil {
		t.Fatal("copy subcommand not found")
	}

	expectedFlags := []string{"account", "id", "path", "name", "dest-id", "dest-path"}
	for _, flagName := range expectedFlags {
		if copyCmd.Flags().Lookup(flagName) == nil {
			t.Errorf("copy missing --%s flag", flagName)
		}
	}
}

func TestUploadCmd_FileFlag(t *testing.T) {
	uploadCmd := findSubcommand(rootCmd, "upload")
	if uploadCmd == nil {
		t.Fatal("upload subcommand not found")
	}

	fileFlag := uploadCmd.Flags().Lookup("file")
	if fileFlag == nil {
		t.Fatal("upload missing --file flag")
	}
	if fileFlag.Shorthand != "f" {
		t.Errorf("upload --file shorthand: expected 'f', got %q", fileFlag.Shorthand)
	}

	// Verify other upload flags
	if uploadCmd.Flags().Lookup("account") == nil {
		t.Error("upload missing --account flag")
	}
	if uploadCmd.Flags().Lookup("id") == nil {
		t.Error("upload missing --id flag")
	}
	if uploadCmd.Flags().Lookup("path") == nil {
		t.Error("upload missing --path flag")
	}
}

func TestMountCmd_HasAllFlags(t *testing.T) {
	mountCmd := findSubcommand(rootCmd, "mount")
	if mountCmd == nil {
		t.Fatal("mount subcommand not found")
	}

	expectedFlags := []string{
		"account",
		"cache-dir", "cache-ttl", "cache-max-entries", "cache-max-size",
		"delta-interval", "max-uploads", "upload-retries", "graph-retries", "http-timeout",
	}
	for _, flagName := range expectedFlags {
		if mountCmd.Flags().Lookup(flagName) == nil {
			t.Errorf("mount missing --%s flag", flagName)
		}
	}
}

// --- helpers ------------------------------------------------------------------

// findSubcommand finds a subcommand by name in a parent command.
func findSubcommand(parent *cobra.Command, name string) *cobra.Command {
	for _, cmd := range parent.Commands() {
		if cmd.Name() == name {
			return cmd
		}
	}
	return nil
}

// subcommandNames returns the names of all subcommands of a command.
func subcommandNames(cmd *cobra.Command) []string {
	names := make([]string, 0, len(cmd.Commands()))
	for _, sub := range cmd.Commands() {
		names = append(names, sub.Name())
	}
	return names
}

// contains checks if a string slice contains a string.
func contains(slice []string, s string) bool {
	for _, item := range slice {
		if item == s {
			return true
		}
	}
	return false
}

// --- version ------------------------------------------------------------------

func TestVersionDefault(t *testing.T) {
	// version defaults to "dev" when not injected via ldflags
	if version != "dev" {
		t.Errorf("expected default version 'dev', got %q", version)
	}
}

// --- rootCmd PersistentPreRun context ----------------------------------------

func TestRootCmd_PersistentPreRunExists(t *testing.T) {
	if rootCmd.PersistentPreRun == nil && rootCmd.PersistentPreRunE == nil {
		t.Error("rootCmd should have PersistentPreRun(E) to initialize the auth manager")
	}
}
