package main

import (
	"slices"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

// --- rootCmd ------------------------------------------------------------------

func TestRootCmd_BasicAttributes(t *testing.T) {
	if rootCmd.Use != "onecloudriver" {
		t.Errorf("expected Use 'onecloudriver', got %q", rootCmd.Use)
	}

	if !strings.Contains(rootCmd.Short, "OneDrive") {
		t.Errorf("expected Short to mention OneDrive, got %q", rootCmd.Short)
	}

	if rootCmd.Version != version {
		t.Errorf("expected Version %q, got %q", version, rootCmd.Version)
	}
}

func TestRootCmd_HasConfigurableLogLevel(t *testing.T) {
	flag := rootCmd.PersistentFlags().Lookup("log-level")
	if flag == nil {
		t.Fatal("root command missing --log-level flag")
	}
	if flag.DefValue != "info" {
		t.Errorf("--log-level default = %q, want %q", flag.DefValue, "info")
	}
	if !strings.Contains(flag.Usage, "trace") || !strings.Contains(flag.Usage, "error") {
		t.Errorf("--log-level help does not list supported levels: %q", flag.Usage)
	}
}

func TestRootCmd_HasAllSubcommands(t *testing.T) {
	expectedCmds := []string{
		"account",
		"mount",
		"service",
		"list",
		"info",
		"download",
		"mkdir",
		"rm",
		"rename",
		"mv",
		"copy",
		"upload",
		"sync",
	}

	cmdNames := make(map[string]bool)
	for _, cmd := range rootCmd.Commands() {
		cmdNames[cmd.Name()] = true
	}

	for _, name := range expectedCmds {
		if !cmdNames[name] {
			t.Errorf("expected subcommand %q not found in rootCmd", name)
		}
	}
}

func TestRootCmd_NoExtraSubcommands(t *testing.T) {
	expectedCmds := map[string]bool{
		"account":    true,
		"mount":      true,
		"service":    true,
		"list":       true,
		"info":       true,
		"download":   true,
		"mkdir":      true,
		"rm":         true,
		"rename":     true,
		"mv":         true,
		"copy":       true,
		"upload":     true,
		"sync":       true,
		"help":       true, // auto-generated by cobra
		"completion": true, // auto-generated by cobra
	}

	for _, cmd := range rootCmd.Commands() {
		if !expectedCmds[cmd.Name()] {
			t.Errorf("unexpected subcommand %q found in rootCmd", cmd.Name())
		}
	}
}

// --- account subcommands ------------------------------------------------------

func TestAccountCmd_HasSubcommands(t *testing.T) {
	accountCmd := findSubcommand(rootCmd, "account")
	if accountCmd == nil {
		t.Fatal("account subcommand not found")
	}

	expected := []string{"add", "list", "remove"}
	names := subcommandNames(accountCmd)

	for _, name := range expected {
		if !slices.Contains(names, name) {
			t.Errorf("expected account subcommand %q not found", name)
		}
	}
}

func TestAccountRemoveCmd_MutuallyExclusiveFlags(t *testing.T) {
	accountCmd := findSubcommand(rootCmd, "account")
	removeCmd := findSubcommand(accountCmd, "remove")
	if removeCmd == nil {
		t.Fatal("account remove subcommand not found")
	}

	purgeFlag := removeCmd.Flags().Lookup("purge")
	keepFlag := removeCmd.Flags().Lookup("keep")

	if purgeFlag == nil {
		t.Error("account remove missing --purge flag")
	}
	if keepFlag == nil {
		t.Error("account remove missing --keep flag")
	}

	// Verify they're booleans
	if purgeFlag != nil && purgeFlag.Value.Type() != "bool" {
		t.Errorf("--purge should be bool, got %s", purgeFlag.Value.Type())
	}
	if keepFlag != nil && keepFlag.Value.Type() != "bool" {
		t.Errorf("--keep should be bool, got %s", keepFlag.Value.Type())
	}
}

// --- service subcommands ------------------------------------------------------

func TestServiceCmd_HasSubcommands(t *testing.T) {
	serviceCmd := findSubcommand(rootCmd, "service")
	if serviceCmd == nil {
		t.Fatal("service subcommand not found")
	}

	expected := []string{"install", "uninstall", "list", "status", "start", "stop", "restart"}
	names := subcommandNames(serviceCmd)

	for _, name := range expected {
		if !slices.Contains(names, name) {
			t.Errorf("expected service subcommand %q not found", name)
		}
	}
}

func TestServiceListCmd_AcceptsNoArguments(t *testing.T) {
	if err := serviceListCmd.Args(serviceListCmd, []string{"unexpected"}); err == nil {
		t.Fatal("service list should reject positional arguments")
	}
	if err := serviceListCmd.Args(serviceListCmd, nil); err != nil {
		t.Fatalf("service list should accept no arguments: %v", err)
	}
}

func TestServiceStatusCmd_AcceptsAtMostOneAccount(t *testing.T) {
	if err := serviceStatusCmd.Args(serviceStatusCmd, []string{"one", "two"}); err == nil {
		t.Fatal("service status should reject more than one account")
	}
	if err := serviceStatusCmd.Args(serviceStatusCmd, []string{"one"}); err != nil {
		t.Fatalf("service status should accept one account: %v", err)
	}
}

func TestServiceInstallCmd_HasAllFlags(t *testing.T) {
	serviceCmd := findSubcommand(rootCmd, "service")
	installCmd := findSubcommand(serviceCmd, "install")
	if installCmd == nil {
		t.Fatal("service install subcommand not found")
	}

	expectedFlags := []string{"mountpoint", "account", "enable", "all"}
	for _, flagName := range expectedFlags {
		if installCmd.Flags().Lookup(flagName) == nil {
			t.Errorf("service install missing --%s flag", flagName)
		}
	}
}

// TestServiceAccountCmds_HasAllFlags covers the service subcommands that share
// the same shape: a single --all flag and cobra.MaximumNArgs(1) for the
// optional account argument (uninstall, start, restart and stop).
func TestServiceAccountCmds_HasAllFlags(t *testing.T) {
	serviceCmd := findSubcommand(rootCmd, "service")
	if serviceCmd == nil {
		t.Fatal("service subcommand not found")
	}

	for _, name := range []string{"uninstall", "start", "restart", "stop"} {
		t.Run(name, func(t *testing.T) {
			cmd := findSubcommand(serviceCmd, name)
			if cmd == nil {
				t.Fatalf("service %s subcommand not found", name)
			}

			if cmd.Flags().Lookup("all") == nil {
				t.Errorf("service %s missing --all flag", name)
			}

			if err := cmd.Args(cmd, []string{}); err != nil {
				t.Fatalf("service %s should not accept zero accounts: %v", name, err)
			}
			if err := cmd.Args(cmd, []string{"one", "two"}); err == nil {
				t.Fatalf("service %s should reject more than one account", name)
			}
			if err := cmd.Args(cmd, []string{"one"}); err != nil {
				t.Fatalf("service %s should accept one account: %v", name, err)
			}
		})
	}
}

// --- command flags ------------------------------------------------------------

// TestCommands_HaveExpectedFlags verifies that each command registers the flags
// it is expected to expose. Commands are looked up in the root command tree, so
// a missing or renamed command fails the test as well.
func TestCommands_HaveExpectedFlags(t *testing.T) {
	cases := map[string][]string{
		"list":     {"account", "output", "id", "path"},
		"info":     {"id", "path", "output", "account"},
		"download": {"account", "id", "path", "output", "output-dir"},
		"mkdir":    {"name"},
		"rm":       {"force"},
		"rename":   {"name", "etag"},
		"mv":       {"account", "id", "path", "dest-id", "dest-path", "etag"},
		"copy":     {"account", "id", "path", "name", "dest-id", "dest-path"},
		"upload":   {"file", "account", "id", "path"},
		"mount": {
			"account",
			"cache-dir", "cache-ttl", "cache-max-entries", "cache-max-size",
			"delta-interval", "max-uploads", "upload-retries", "graph-retries", "http-timeout",
		},
	}
	// Each test case is a subtest, so that a failure in one command does not prevent
	// the other commands from being tested.
	// name is the command name, flags is the list of expected flags for that command.
	for name, flags := range cases {
		t.Run(name, func(t *testing.T) {
			cmd := findSubcommand(rootCmd, name)
			if cmd == nil {
				t.Fatalf("%s subcommand not found", name)
			}
			for _, flagName := range flags {
				if cmd.Flags().Lookup(flagName) == nil {
					t.Errorf("%s missing --%s flag", name, flagName)
				}
			}
		})
	}
}

// TestCommands_FlagShorthands verifies the shorthand of the flags that expose
// one. An empty shorthand asserts the flag is registered without a shorthand,
// which is intentional for the item commands (only info exposes -i/-p).
func TestCommands_FlagShorthands(t *testing.T) {
	cases := []struct {
		cmd       string
		flag      string
		shorthand string
	}{
		{"list", "account", "a"},
		{"list", "output", "o"},
		{"list", "id", ""},
		{"list", "path", ""},
		{"mkdir", "name", "n"},
		{"rm", "force", "f"},
		{"rename", "name", "n"},
		{"upload", "file", "f"},
	}

	for _, tc := range cases {
		t.Run(tc.cmd+"_"+tc.flag, func(t *testing.T) {
			cmd := findSubcommand(rootCmd, tc.cmd)
			if cmd == nil {
				t.Fatalf("%s subcommand not found", tc.cmd)
			}
			flag := cmd.Flags().Lookup(tc.flag)
			if flag == nil {
				t.Fatalf("%s missing --%s flag", tc.cmd, tc.flag)
			}
			if flag.Shorthand != tc.shorthand {
				t.Errorf("%s --%s shorthand: expected %q, got %q", tc.cmd, tc.flag, tc.shorthand, flag.Shorthand)
			}
		})
	}
}

// --- helpers ------------------------------------------------------------------

// findSubcommand finds a subcommand by name in a parent command.
func findSubcommand(parent *cobra.Command, name string) *cobra.Command {
	for _, cmd := range parent.Commands() {
		if cmd.Name() == name {
			return cmd
		}
	}
	return nil
}

// subcommandNames returns the names of all subcommands of a command.
func subcommandNames(cmd *cobra.Command) []string {
	names := make([]string, 0, len(cmd.Commands()))
	for _, sub := range cmd.Commands() {
		names = append(names, sub.Name())
	}
	return names
}

// --- version ------------------------------------------------------------------

func TestVersionDefault(t *testing.T) {
	// version defaults to "dev" when not injected via ldflags
	if version != "dev" {
		t.Errorf("expected default version 'dev', got %q", version)
	}
}

// --- rootCmd PersistentPreRun context ----------------------------------------

func TestRootCmd_PersistentPreRunExists(t *testing.T) {
	if rootCmd.PersistentPreRun == nil && rootCmd.PersistentPreRunE == nil {
		t.Error("rootCmd should have PersistentPreRun(E) to initialize the auth manager")
	}
}
